# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fuzzy_gui2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1164, 865)
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(10, 10, 1131, 20))
        self.label_33.setTextFormat(QtCore.Qt.AutoText)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(Form)
        self.label_34.setGeometry(QtCore.QRect(10, 70, 591, 20))
        self.label_34.setTextFormat(QtCore.Qt.AutoText)
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.deploy_btn = QtWidgets.QPushButton(Form)
        self.deploy_btn.setGeometry(QtCore.QRect(10, 330, 551, 25))
        self.deploy_btn.setObjectName("deploy_btn")
        self.label_49 = QtWidgets.QLabel(Form)
        self.label_49.setGeometry(QtCore.QRect(590, 230, 511, 20))
        self.label_49.setTextFormat(QtCore.Qt.AutoText)
        self.label_49.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.calc_btn = QtWidgets.QPushButton(Form)
        self.calc_btn.setGeometry(QtCore.QRect(600, 330, 541, 25))
        self.calc_btn.setObjectName("calc_btn")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(600, 250, 541, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_50 = QtWidgets.QLabel(self.layoutWidget)
        self.label_50.setObjectName("label_50")
        self.gridLayout_6.addWidget(self.label_50, 0, 0, 1, 1)
        self.input_vel = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_vel.setObjectName("input_vel")
        self.gridLayout_6.addWidget(self.input_vel, 0, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget)
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 1, 0, 1, 1)
        self.input_dis = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_dis.setObjectName("input_dis")
        self.gridLayout_6.addWidget(self.input_dis, 1, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(600, 100, 160, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_v_verlow = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_v_verlow.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_v_verlow.setObjectName("lbl_v_verlow")
        self.gridLayout_4.addWidget(self.lbl_v_verlow, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.lbl_v_low = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_v_low.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_v_low.setObjectName("lbl_v_low")
        self.gridLayout_4.addWidget(self.lbl_v_low, 1, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 3, 0, 1, 1)
        self.lbl_v_high = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_v_high.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_v_high.setObjectName("lbl_v_high")
        self.gridLayout_4.addWidget(self.lbl_v_high, 3, 1, 1, 1)
        self.lbl_v_med = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_v_med.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_v_med.setObjectName("lbl_v_med")
        self.gridLayout_4.addWidget(self.lbl_v_med, 2, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 4, 0, 1, 1)
        self.lbl_v_verhigh = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_v_verhigh.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_v_verhigh.setObjectName("lbl_v_verhigh")
        self.gridLayout_4.addWidget(self.lbl_v_verhigh, 4, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(790, 100, 160, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbl_d_verlow = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_d_verlow.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_d_verlow.setObjectName("lbl_d_verlow")
        self.gridLayout_5.addWidget(self.lbl_d_verlow, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 1, 0, 1, 1)
        self.lbl_d_low = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_d_low.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_d_low.setObjectName("lbl_d_low")
        self.gridLayout_5.addWidget(self.lbl_d_low, 1, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 2, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 0, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.gridLayout_5.addWidget(self.label_52, 3, 0, 1, 1)
        self.lbl_d_high = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_d_high.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_d_high.setObjectName("lbl_d_high")
        self.gridLayout_5.addWidget(self.lbl_d_high, 3, 1, 1, 1)
        self.lbl_d_med = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_d_med.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_d_med.setObjectName("lbl_d_med")
        self.gridLayout_5.addWidget(self.lbl_d_med, 2, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_55.setObjectName("label_55")
        self.gridLayout_5.addWidget(self.label_55, 4, 0, 1, 1)
        self.lbl_d_verhigh = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_d_verhigh.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_d_verhigh.setObjectName("lbl_d_verhigh")
        self.gridLayout_5.addWidget(self.lbl_d_verhigh, 4, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(980, 100, 160, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lbl_b_verlow = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_b_verlow.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_b_verlow.setObjectName("lbl_b_verlow")
        self.gridLayout_7.addWidget(self.lbl_b_verlow, 0, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_58.setObjectName("label_58")
        self.gridLayout_7.addWidget(self.label_58, 1, 0, 1, 1)
        self.lbl_b_low = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_b_low.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_b_low.setObjectName("lbl_b_low")
        self.gridLayout_7.addWidget(self.lbl_b_low, 1, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_60.setObjectName("label_60")
        self.gridLayout_7.addWidget(self.label_60, 2, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_61.setObjectName("label_61")
        self.gridLayout_7.addWidget(self.label_61, 0, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_62.setObjectName("label_62")
        self.gridLayout_7.addWidget(self.label_62, 3, 0, 1, 1)
        self.lbl_b_high = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_b_high.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_b_high.setObjectName("lbl_b_high")
        self.gridLayout_7.addWidget(self.lbl_b_high, 3, 1, 1, 1)
        self.lbl_b_med = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_b_med.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_b_med.setObjectName("lbl_b_med")
        self.gridLayout_7.addWidget(self.lbl_b_med, 2, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_65.setObjectName("label_65")
        self.gridLayout_7.addWidget(self.label_65, 4, 0, 1, 1)
        self.lbl_b_verhigh = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbl_b_verhigh.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_b_verhigh.setObjectName("lbl_b_verhigh")
        self.gridLayout_7.addWidget(self.lbl_b_verhigh, 4, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(Form)
        self.label_67.setGeometry(QtCore.QRect(600, 70, 161, 16))
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(Form)
        self.label_68.setGeometry(QtCore.QRect(790, 70, 161, 16))
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(Form)
        self.label_69.setGeometry(QtCore.QRect(980, 70, 161, 16))
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 370, 1131, 20))
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(10, 50, 1131, 20))
        self.line_2.setLineWidth(6)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(570, 70, 20, 301))
        self.line_3.setLineWidth(4)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_35 = QtWidgets.QLabel(Form)
        self.label_35.setGeometry(QtCore.QRect(10, 390, 1131, 20))
        self.label_35.setTextFormat(QtCore.Qt.AutoText)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_output = QtWidgets.QLabel(Form)
        self.label_output.setGeometry(QtCore.QRect(590, 790, 551, 61))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_output.setFont(font)
        self.label_output.setScaledContents(True)
        self.label_output.setAlignment(QtCore.Qt.AlignCenter)
        self.label_output.setObjectName("label_output")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 300, 551, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.line_vel_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_vel_max.setObjectName("line_vel_max")
        self.horizontalLayout.addWidget(self.line_vel_max)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_3.addWidget(self.label_17)
        self.line_dis_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_dis_max.setObjectName("line_dis_max")
        self.horizontalLayout_3.addWidget(self.line_dis_max)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.line_brake_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_brake_max.setObjectName("line_brake_max")
        self.horizontalLayout_6.addWidget(self.line_brake_max)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(590, 430, 551, 341))
        self.layoutWidget2.setObjectName("layoutWidget2")

        self.ver_lay1_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.ver_lay1_2.setContentsMargins(0, 0, 0, 0)
        self.ver_lay1_2.setObjectName("ver_lay1_2")

        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 91, 551, 16))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_5.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_5.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_5.addWidget(self.label_32)
        self.layoutWidget4 = QtWidgets.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(12, 134, 547, 161))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_vel_low_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_vel_low_max.setObjectName("line_vel_low_max")
        self.gridLayout.addWidget(self.line_vel_low_max, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.line_vel_low_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_vel_low_min.setObjectName("line_vel_low_min")
        self.gridLayout.addWidget(self.line_vel_low_min, 1, 1, 1, 1)
        self.line_vel_med_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_vel_med_max.setObjectName("line_vel_med_max")
        self.gridLayout.addWidget(self.line_vel_med_max, 2, 2, 1, 1)
        self.line_vel_high_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_vel_high_max.setObjectName("line_vel_high_max")
        self.gridLayout.addWidget(self.line_vel_high_max, 3, 2, 1, 1)
        self.line_vel_verlow_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_vel_verlow_min.setObjectName("line_vel_verlow_min")
        self.gridLayout.addWidget(self.line_vel_verlow_min, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.line_vel_verhigh_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_vel_verhigh_min.setObjectName("line_vel_verhigh_min")
        self.gridLayout.addWidget(self.line_vel_verhigh_min, 4, 1, 1, 1)
        self.line_vel_verlow_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_vel_verlow_max.setObjectName("line_vel_verlow_max")
        self.gridLayout.addWidget(self.line_vel_verlow_max, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.line_vel_high_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_vel_high_min.setObjectName("line_vel_high_min")
        self.gridLayout.addWidget(self.line_vel_high_min, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.line_vel_verhigh_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_vel_verhigh_max.setObjectName("line_vel_verhigh_max")
        self.gridLayout.addWidget(self.line_vel_verhigh_max, 4, 2, 1, 1)
        self.line_vel_med_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_vel_med_min.setObjectName("line_vel_med_min")
        self.gridLayout.addWidget(self.line_vel_med_min, 2, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.line_dis_low_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_dis_low_max.setObjectName("line_dis_low_max")
        self.gridLayout_2.addWidget(self.line_dis_low_max, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.line_dis_low_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_dis_low_min.setObjectName("line_dis_low_min")
        self.gridLayout_2.addWidget(self.line_dis_low_min, 1, 1, 1, 1)
        self.line_dis_med_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_dis_med_max.setObjectName("line_dis_med_max")
        self.gridLayout_2.addWidget(self.line_dis_med_max, 2, 2, 1, 1)
        self.line_dis_high_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_dis_high_max.setObjectName("line_dis_high_max")
        self.gridLayout_2.addWidget(self.line_dis_high_max, 3, 2, 1, 1)
        self.line_dis_verlow_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_dis_verlow_min.setObjectName("line_dis_verlow_min")
        self.gridLayout_2.addWidget(self.line_dis_verlow_min, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.line_dis_med_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_dis_med_min.setObjectName("line_dis_med_min")
        self.gridLayout_2.addWidget(self.line_dis_med_min, 2, 1, 1, 1)
        self.line_dis_verhigh_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_dis_verhigh_min.setObjectName("line_dis_verhigh_min")
        self.gridLayout_2.addWidget(self.line_dis_verhigh_min, 4, 1, 1, 1)
        self.line_dis_verlow_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_dis_verlow_max.setObjectName("line_dis_verlow_max")
        self.gridLayout_2.addWidget(self.line_dis_verlow_max, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.line_dis_high_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_dis_high_min.setObjectName("line_dis_high_min")
        self.gridLayout_2.addWidget(self.line_dis_high_min, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.line_dis_verhigh_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_dis_verhigh_max.setObjectName("line_dis_verhigh_max")
        self.gridLayout_2.addWidget(self.line_dis_verhigh_max, 4, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.line_brake_low_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_brake_low_max.setObjectName("line_brake_low_max")
        self.gridLayout_3.addWidget(self.line_brake_low_max, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.line_brake_low_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_brake_low_min.setObjectName("line_brake_low_min")
        self.gridLayout_3.addWidget(self.line_brake_low_min, 1, 1, 1, 1)
        self.line_brake_med_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_brake_med_max.setObjectName("line_brake_med_max")
        self.gridLayout_3.addWidget(self.line_brake_med_max, 2, 2, 1, 1)
        self.line_brake_high_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_brake_high_max.setObjectName("line_brake_high_max")
        self.gridLayout_3.addWidget(self.line_brake_high_max, 3, 2, 1, 1)
        self.line_brake_verlow_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_brake_verlow_min.setObjectName("line_brake_verlow_min")
        self.gridLayout_3.addWidget(self.line_brake_verlow_min, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.line_brake_med_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_brake_med_min.setObjectName("line_brake_med_min")
        self.gridLayout_3.addWidget(self.line_brake_med_min, 2, 1, 1, 1)
        self.line_brake_verhigh_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_brake_verhigh_min.setObjectName("line_brake_verhigh_min")
        self.gridLayout_3.addWidget(self.line_brake_verhigh_min, 4, 1, 1, 1)
        self.line_brake_verlow_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_brake_verlow_max.setObjectName("line_brake_verlow_max")
        self.gridLayout_3.addWidget(self.line_brake_verlow_max, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.line_brake_high_min = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_brake_high_min.setObjectName("line_brake_high_min")
        self.gridLayout_3.addWidget(self.line_brake_high_min, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 4, 0, 1, 1)
        self.line_brake_verhigh_max = QtWidgets.QLineEdit(self.layoutWidget4)
        self.line_brake_verhigh_max.setObjectName("line_brake_verhigh_max")
        self.gridLayout_3.addWidget(self.line_brake_verhigh_max, 4, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.layoutWidget5 = QtWidgets.QWidget(Form)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 110, 551, 16))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_4.addWidget(self.label_26)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_4.addWidget(self.label_21)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_4.addWidget(self.label_28)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_4.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_4.addWidget(self.label_29)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_4.addWidget(self.label_25)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_4.addWidget(self.label_27)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 430, 561, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.ver_lay1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.ver_lay1.setContentsMargins(30, 3, 3, 3)
        self.ver_lay1.setObjectName("ver_lay1")

        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(570, 420, 20, 431))
        self.line_4.setLineWidth(4)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_41 = QtWidgets.QLabel(Form)
        self.label_41.setGeometry(QtCore.QRect(11, 411, 561, 16))
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_46 = QtWidgets.QLabel(Form)
        self.label_46.setGeometry(QtCore.QRect(590, 410, 551, 16))
        self.label_46.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_33.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">BRAKE SIMULATOR</span></p></body></html>"))
        self.label_34.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Configuration</span></p></body></html>"))
        self.deploy_btn.setText(_translate("Form", "Deploy"))
        self.label_49.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Input</span></p></body></html>"))
        self.calc_btn.setText(_translate("Form", "Calculate"))
        self.label_50.setText(_translate("Form", "Velocity (m/s) :"))
        self.label_51.setText(_translate("Form", "Distance (m) :"))
        self.lbl_v_verlow.setText(_translate("Form", "[0:10.0:15.0]"))
        self.label_19.setText(_translate("Form", "Slow"))
        self.lbl_v_low.setText(_translate("Form", "[10.0:22.5:35.0]"))
        self.label_38.setText(_translate("Form", "Medium"))
        self.label_18.setText(_translate("Form", "Very slow"))
        self.label_40.setText(_translate("Form", "Fast"))
        self.lbl_v_high.setText(_translate("Form", "[55.0:67.5:80.0]"))
        self.lbl_v_med.setText(_translate("Form", "[30.0:47.5:65.0]"))
        self.label_42.setText(_translate("Form", "Very fast"))
        self.lbl_v_verhigh.setText(_translate("Form", "[70.0:75.0:85.0]"))
        self.lbl_d_verlow.setText(_translate("Form", "[0:15.0:30.0]"))
        self.label_45.setText(_translate("Form", "Near"))
        self.lbl_d_low.setText(_translate("Form", "[15.0:30.0:45.0]"))
        self.label_47.setText(_translate("Form", "Medium"))
        self.label_48.setText(_translate("Form", "Very near"))
        self.label_52.setText(_translate("Form", "Far"))
        self.lbl_d_high.setText(_translate("Form", "[60.0:75.0:90.0]"))
        self.lbl_d_med.setText(_translate("Form", "[35.0:55.0:75.0]"))
        self.label_55.setText(_translate("Form", "Very far"))
        self.lbl_d_verhigh.setText(_translate("Form", "[80.0:85.0:90.0]"))
        self.lbl_b_verlow.setText(_translate("Form", "[0:40.0:50.0]"))
        self.label_58.setText(_translate("Form", "Low"))
        self.lbl_b_low.setText(_translate("Form", "[40.0:100.0:160.0]"))
        self.label_60.setText(_translate("Form", "Medium"))
        self.label_61.setText(_translate("Form", "Very low"))
        self.label_62.setText(_translate("Form", "High"))
        self.lbl_b_high.setText(_translate("Form", "[240.0:300.0:360.0]"))
        self.lbl_b_med.setText(_translate("Form", "[120.0:190.0:280.0]"))
        self.label_65.setText(_translate("Form", "Very High"))
        self.lbl_b_verhigh.setText(_translate("Form", "[320.0:330.0:340.0]"))
        self.label_67.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Velocity (m/s)</span></p></body></html><?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QWidget\" name=\"gridLayoutWidget_2\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>810</x>\n"
"     <y>90</y>\n"
"     <width>160</width>\n"
"     <height>91</height>\n"
"    </rect>\n"
"   </property>\n"
"   <layout class=\"QGridLayout\" name=\"gridLayout_5\">\n"
"    <item row=\"0\" column=\"1\">\n"
"     <widget class=\"QLabel\" name=\"label_44\">\n"
"      <property name=\"text\">\n"
"       <string>TextLabel</string>\n"
"      </property>\n"
"     </widget>\n"
"    </item>\n"
"    <item row=\"1\" column=\"0\">\n"
"     <widget class=\"QLabel\" name=\"label_45\">\n"
"      <property name=\"text\">\n"
"       <string>TextLabel</string>\n"
"      </property>\n"
"     </widget>\n"
"    </item>\n"
"    <item row=\"1\" column=\"1\">\n"
"     <widget class=\"QLabel\" name=\"label_46\">\n"
"      <property name=\"text\">\n"
"       <string>TextLabel</string>\n"
"      </property>\n"
"     </widget>\n"
"    </item>\n"
"    <item row=\"2\" column=\"0\">\n"
"     <widget class=\"QLabel\" name=\"label_47\">\n"
"      <property name=\"text\">\n"
"       <string>TextLabel</string>\n"
"      </property>\n"
"     </widget>\n"
"    </item>\n"
"    <item row=\"0\" column=\"0\">\n"
"     <widget class=\"QLabel\" name=\"label_48\">\n"
"      <property name=\"text\">\n"
"       <string>TextLabel</string>\n"
"      </property>\n"
"     </widget>\n"
"    </item>\n"
"    <item row=\"3\" column=\"0\">\n"
"     <widget class=\"QLabel\" name=\"label_52\">\n"
"      <property name=\"text\">\n"
"       <string>TextLabel</string>\n"
"      </property>\n"
"     </widget>\n"
"    </item>\n"
"    <item row=\"3\" column=\"1\">\n"
"     <widget class=\"QLabel\" name=\"label_53\">\n"
"      <property name=\"text\">\n"
"       <string>TextLabel</string>\n"
"      </property>\n"
"     </widget>\n"
"    </item>\n"
"    <item row=\"2\" column=\"1\">\n"
"     <widget class=\"QLabel\" name=\"label_54\">\n"
"      <property name=\"text\">\n"
"       <string>TextLabel</string>\n"
"      </property>\n"
"     </widget>\n"
"    </item>\n"
"    <item row=\"4\" column=\"0\">\n"
"     <widget class=\"QLabel\" name=\"label_55\">\n"
"      <property name=\"text\">\n"
"       <string>TextLabel</string>\n"
"      </property>\n"
"     </widget>\n"
"    </item>\n"
"    <item row=\"4\" column=\"1\">\n"
"     <widget class=\"QLabel\" name=\"label_56\">\n"
"      <property name=\"text\">\n"
"       <string>TextLabel</string>\n"
"      </property>\n"
"     </widget>\n"
"    </item>\n"
"   </layout>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
""))
        self.label_68.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Distance (m)</span></p><p><br/></p></body></html>"))
        self.label_69.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Break Force (m/s</span><span style=\" font-weight:600; vertical-align:super;\">2</span><span style=\" font-weight:600;\">)</span></p><p><br/></p></body></html>"))
        self.label_35.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">RESULT</span></p></body></html>"))
        self.label_output.setText(_translate("Form", "0.0 m/s^2"))
        self.label_16.setText(_translate("Form", "Max value"))
        self.label_17.setText(_translate("Form", "Max value"))
        self.label_20.setText(_translate("Form", "Max value"))
        self.label_30.setText(_translate("Form", "Velocity (m/s)"))
        self.label_31.setText(_translate("Form", "Distance (m)"))
        self.label_32.setText(_translate("Form", "Braking Force (m/s^2)"))
        self.label.setText(_translate("Form", "Very near"))
        self.label_2.setText(_translate("Form", "Near"))
        self.label_4.setText(_translate("Form", "Far"))
        self.label_3.setText(_translate("Form", "Medium"))
        self.label_5.setText(_translate("Form", "Very far"))
        self.label_6.setText(_translate("Form", "Very slow"))
        self.label_7.setText(_translate("Form", "slow"))
        self.label_8.setText(_translate("Form", "Fast"))
        self.label_9.setText(_translate("Form", "Medium"))
        self.label_10.setText(_translate("Form", "Very fast"))
        self.label_11.setText(_translate("Form", "Very soft"))
        self.label_12.setText(_translate("Form", "Soft"))
        self.label_13.setText(_translate("Form", "Hard"))
        self.label_14.setText(_translate("Form", "Medium"))
        self.label_15.setText(_translate("Form", "Very hard"))
        self.label_21.setText(_translate("Form", "min"))
        self.label_28.setText(_translate("Form", "max"))
        self.label_23.setText(_translate("Form", "min"))
        self.label_24.setText(_translate("Form", "max"))
        self.label_25.setText(_translate("Form", "min"))
        self.label_27.setText(_translate("Form", "max"))
        self.label_41.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Input</span></p></body></html>"))
        self.label_46.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Output</span></p></body></html>"))

